In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


# 1D ARRAY

In [6]:
a=np.array([1,2,3,4,5])
a.ndim


1

In [7]:
a.shape

(5,)

In [8]:
len(a)

5

# 2D array

In [14]:
b=np.array([[1,2,3],[12,3,32]])
b.ndim

2

In [16]:
b.shape


(2, 3)

In [19]:
len(b)

2

# 3D array

In [17]:
c=np.array([[[1,2,3],[12,3,32]],[[1,2,3],[12,3,32]]])
b.ndim

2

In [18]:
c

array([[[ 1,  2,  3],
        [12,  3, 32]],

       [[ 1,  2,  3],
        [12,  3, 32]]])

In [21]:
len(c)

2

In [22]:
c.shape

(2, 2, 3)

In [25]:
a=np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b=np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

# get entire output

In [66]:
np.set_printoptions(threshold=np.inf)
a=np.linspace(2,15,11111)
print(a)

[ 2.          2.00117012  2.00234023  2.00351035  2.00468047  2.00585059
  2.0070207   2.00819082  2.00936094  2.01053105  2.01170117  2.01287129
  2.0140414   2.01521152  2.01638164  2.01755176  2.01872187  2.01989199
  2.02106211  2.02223222  2.02340234  2.02457246  2.02574257  2.02691269
  2.02808281  2.02925293  2.03042304  2.03159316  2.03276328  2.03393339
  2.03510351  2.03627363  2.03744374  2.03861386  2.03978398  2.0409541
  2.04212421  2.04329433  2.04446445  2.04563456  2.04680468  2.0479748
  2.04914491  2.05031503  2.05148515  2.05265527  2.05382538  2.0549955
  2.05616562  2.05733573  2.05850585  2.05967597  2.06084608  2.0620162
  2.06318632  2.06435644  2.06552655  2.06669667  2.06786679  2.0690369
  2.07020702  2.07137714  2.07254725  2.07371737  2.07488749  2.07605761
  2.07722772  2.07839784  2.07956796  2.08073807  2.08190819  2.08307831
  2.08424842  2.08541854  2.08658866  2.08775878  2.08892889  2.09009901
  2.09126913  2.09243924  2.09360936  2.09477948  2.0959

In [36]:
len(a)

11111

In [41]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
a.dtype

dtype('float64')

In [45]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
a-c

array([[-1.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0., -1.]])

In [71]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [51]:
len(np.diag(a))

4

In [52]:
np.diag(a).shape

(4,)

In [53]:
a.ndim

2

In [54]:
np.diag(a)

array([1, 2, 3, 4])

In [57]:
a[0][0]

1

In [58]:
a[1][1]

2

In [60]:
a[1][2]=3

In [72]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [73]:
a[1][2]=4
a

array([[1, 0, 0, 0],
       [0, 2, 4, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [74]:
b=a[1:8:2]

In [75]:
b

array([[0, 2, 4, 0],
       [0, 0, 0, 4]])

In [76]:
np.shares_memory(a,b)

True

In [79]:
a=np.arange(10)
c=a[::2].copy()
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
c

array([0, 2, 4, 6, 8])

In [81]:
np.shares_memory(a,c)

False

In [94]:
ma=(a%2==0)
a


array([ 0, 12, 19,  5, 19,  9, 17,  6,  4,  2,  7,  2,  6, 17,  7])

In [91]:
a=np.random.randint(0,20,15)
a

array([ 0, 12, 19,  5, 19,  9, 17,  6,  4,  2,  7,  2,  6, 17,  7])

In [95]:
ma=(a%2==0)
g=a[ma]
g

array([ 0, 12,  6,  4,  2,  2,  6])

In [96]:
a[ma]=2

In [97]:
a


array([ 2,  2, 19,  5, 19,  9, 17,  2,  2,  2,  7,  2,  2, 17,  7])

In [98]:
a[[1,2,3]]

array([ 2, 19,  5])

In [99]:
a[[4,8]]=10-3

In [100]:
a

array([ 2,  2, 19,  5,  7,  9, 17,  2,  7,  2,  7,  2,  2, 17,  7])