In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a+1


array([2, 3, 4, 5])

In [7]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [10]:
b=np.ones(4)
b

array([1., 1., 1., 1.])

In [11]:
a-b


array([0., 1., 2., 3.])

In [15]:
c = np.array([1,2,3])

print(c * c)
print("*****************")
print(c.dot(c)) #matrix multiplication


[1 4 9]
*****************
14


In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a <b

array([ True, False, False, False])

In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a != b

array([ True, False,  True, False])

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [21]:
np.array_equal(c, a)

True

In [25]:
a = np.array([2, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [27]:
np.logical_and(a, b)

array([ True, False, False, False])

In [28]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
a = np.arange(5)

np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [30]:
a = np.arange(5)

np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [31]:
np.log(a)

C:\Users\Dileep\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [32]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [33]:
np.sum(a)

10

In [35]:
a=np.array([[1,2,3],[3,4,5]])
a.sum(axis=0)

array([4, 6, 8])

In [36]:
a.sum(axis=1)

array([ 6, 12])

In [40]:
a.min(axis=0)

array([1, 2, 3])

In [39]:
a.max(axis=1)

array([3, 5])

In [41]:
a.argmin()

0

In [43]:
a.argmax()

5

In [44]:
a[5]

IndexError: index 5 is out of bounds for axis 0 with size 2

In [45]:
np.all([True,False,True])

False

In [46]:
np.any([True,False,True])

True

In [49]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
print(a<=b)
print(b<=c)
print(((a <= b) & (b <= c)))
((a <= b) & (b <= c)).all()

[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]


True

In [50]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [52]:
np.median(x)

1.5

In [56]:
np.median(y,axis=1)

array([2., 5.])

In [57]:
x.std()

0.82915619758885

In [58]:
data = np.loadtxt('populations.txt')

In [59]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [60]:
data.T

array([[ 1900.,  1901.,  1902.,  1903.,  1904.,  1905.,  1906.,  1907.,
         1908.,  1909.,  1910.,  1911.,  1912.,  1913.,  1914.,  1915.,
         1916.,  1917.,  1918.,  1919.,  1920.],
       [30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
        22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
        11200.,  7600., 14600., 16200., 24700.],
       [ 4000.,  6100.,  9800., 35200., 59400., 41700., 19000., 13000.,
         8300.,  9100.,  7400.,  8000., 12300., 19500., 45700., 51100.,
        29700., 15800.,  9700., 10100.,  8600.],
       [48300., 48200., 41500., 38200., 40600., 39800., 38600., 42300.,
        44500., 42100., 46000., 46800., 43800., 40900., 39400., 39000.,
        36700., 41800., 43300., 41300., 47300.]])

In [61]:
year, hares, lynxes, carrots = data.T #columns to variables


In [62]:
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [63]:
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [64]:
print(hares)

[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]


In [66]:
populations=data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [67]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [68]:
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [69]:
populations.max(axis=0)

array([77400., 59400., 48300.])

# BROADCASTING

In [72]:
a = np.tile(np.arange(0, 40, 10), (3,1))
print(a)

print("*************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [73]:
b=np.array([0,1,2])

In [74]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [75]:
a = np.arange(0, 40, 10)

a.shape

(4,)

In [82]:
a=a.T

In [83]:
a+b

ValueError: operands could not be broadcast together with shapes (1,1,4) (3,) 

# converting to other dimension array

In [80]:
a=a[:,np.newaxis]
a

array([[[ 0]],

       [[10]],

       [[20]],

       [[30]]])

In [81]:
a+b

array([[[ 0,  1,  2]],

       [[10, 11, 12]],

       [[20, 21, 22]],

       [[30, 31, 32]]])

In [84]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [86]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [88]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [89]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [91]:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=0)
b

array([[2, 3, 2],
       [5, 4, 6]])

In [92]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [93]:
a[j]

array([1, 2, 3, 4])